server:
  port: 9001
spring:
  application:
    name: jbs-feign
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
feign:
  hystrix:
    enabled: false


ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000